os:
  - linux
  - osx

language: cpp

env:
  global:
    - secure: "x+x2IMHk0IJKuvDAWcNMi5ifR0dNwpvAkM2axK67YqN2zb0CJzpj87daiEGvf+4268gHk5nBtHQtVxTIjk6B6LmUnya6OwOcs55ZBMrkgc6NiWVxB9+i6n2phdVNbXogWknOBDZhQqTtqqdvbQBJAO3UppdFrDZQF3eb9j+YWMs="
    - secure: "lijVVp4jRIfDkV67yPFdANoAv9oONJSISM/QO7uScMyNUkyDKwCgZbuFsOziJsqZUyGbM3GFCdSK7ufpzM3mlEFQyPckaPCnHyifgzixLlWTn7Krijgt5jMFGqwbSONqLENBhUJi5eAmj2m2lP3Pdmg4U4PPAOTwd5EQvY8uwRU="

before_install:
  # Linux steps
  - '[ "$TRAVIS_OS_NAME" != linux ] || curl http://download.opensuse.org/repositories/science:/dlr/xUbuntu_12.04/Release.key | sudo apt-key add - '
  - '[ "$TRAVIS_OS_NAME" != linux ] || echo "deb http://download.opensuse.org/repositories/science:/dlr/xUbuntu_12.04/ /" | sudo tee -a /etc/apt/sources.list '
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo add-apt-repository ppa:george-edison55/precise-backports -y'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get update -qq '
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get install -y --force-yes libtixi-dev liboce-dev cmake cmake-data sshpass'
# oce ships a faulty config file, we have to remove it and use standard opencascade detection
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo rm /usr/lib/oce-*/OCEConfig.cmake '
  # macOS steps
  - '[ "$TRAVIS_OS_NAME" != osx ] || export MACOSX_DEPLOYMENT_TARGET=10.8'
  - '[ "$TRAVIS_OS_NAME" != osx ] || ci/travis/get_qt_macOS.sh'
  - '[ "$TRAVIS_OS_NAME" != osx ] || /usr/bin/curl -o sshpass-macOS.tar.gz -L https://sourceforge.net/projects/tigl/files/Thirdparty/sshpass-macOS.tar.gz'
  - '[ "$TRAVIS_OS_NAME" != osx ] || /usr/bin/curl -o oce.0.17.2.macos_static.tar.gz -L https://sourceforge.net/projects/tigl/files/Thirdparty/oce.0.17.2.macos_static.tar.gz'
  - '[ "$TRAVIS_OS_NAME" != osx ] || /usr/bin/curl -O -L https://github.com/DLR-SC/tixi/releases/download/v2.2.4/TIXI-2.2.4-macOS.tar.gz '
  - '[ "$TRAVIS_OS_NAME" != osx ] || tar xf sshpass-macOS.tar.gz -C /tmp && export PATH=$PATH:/tmp'
  - '[ "$TRAVIS_OS_NAME" != osx ] || tar xf oce.0.17.2.macos_static.tar.gz'
  - '[ "$TRAVIS_OS_NAME" != osx ] || tar xf TIXI-2.2.4-macOS.tar.gz '
  # If a tag/release is build, disable the nighty build flag
  - export TIGL_NIGHTLY=$([ "$TRAVIS_EVENT_TYPE" == "cron" ] && echo "ON" || echo "OFF")

before_script:
  - mkdir build
  - cd build

script:
  - '[ "$TRAVIS_OS_NAME" != osx ] || export CMAKE_PREFIX_PATH=`pwd`/../TIXI-2.2.4-macOS:`pwd`/../oce.0.17.2.macos_static:`pwd`/../Qt5.4_clang64_macOS'
  - '[ "$TRAVIS_OS_NAME" != osx ] || export CXXFLAGS=-Wno-inconsistent-missing-override '
  - '[ "$TRAVIS_OS_NAME" != linux ] || jdk_switcher use oraclejdk8'
  - cmake -DTIGL_BUILD_TESTS=ON -DTIGL_NIGHTLY=$TIGL_NIGHTLY -DTIGL_BINDINGS_MATLAB=ON -DTIGL_BINDINGS_JAVA=ON -DCMAKE_INSTALL_PREFIX=`pwd`/install ..
  - make -j 4
  - make install
  - '[ "$TRAVIS_OS_NAME" != osx ] || make package'
  - '[ "$TRAVIS_OS_NAME" != osx ] || export DYLD_LIBRARY_PATH=`pwd`/../TIXI-2.2.4-macOS/lib '
  - cd tests
  - ./TiGL-unittests --gtest_output=xml
  - cd ..
  - TERM=dumb make tigl-java-demo

after_success:
    - ../ci/travis/deploy.sh
