os:
  - linux
  - osx

language: cpp

before_install:
  # Linux steps
  - '[ "$TRAVIS_OS_NAME" != linux ] || curl http://download.opensuse.org/repositories/science:/dlr/xUbuntu_12.04/Release.key | sudo apt-key add - '
  - '[ "$TRAVIS_OS_NAME" != linux ] || echo "deb http://download.opensuse.org/repositories/science:/dlr/xUbuntu_12.04/ /" | sudo tee -a /etc/apt/sources.list '
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo add-apt-repository ppa:george-edison55/precise-backports -y'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get update -qq '
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get install -y --force-yes libtixi-dev liboce-dev cmake cmake-data'
# oce ships a faulty config file, we have to remove it and use standard opencascade detection
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo rm /usr/lib/oce-*/OCEConfig.cmake '
  # macOS steps
  - '[ "$TRAVIS_OS_NAME" != osx ] || export MACOSX_DEPLOYMENT_TARGET=10.8'
  - '[ "$TRAVIS_OS_NAME" != osx ] || /usr/bin/curl -o Qt5.4_clang64_macOS.tar.gz -L https://sourceforge.net/projects/tigl/files/Thirdparty/Qt5.4_clang64_macOS.tar.gz'
  - '[ "$TRAVIS_OS_NAME" != osx ] || /usr/bin/curl -o oce.0.17.2.macos_static.tar.gz -L https://sourceforge.net/projects/tigl/files/Thirdparty/oce.0.17.2.macos_static.tar.gz'
  - '[ "$TRAVIS_OS_NAME" != osx ] || /usr/bin/curl -O -L https://github.com/DLR-SC/tixi/releases/download/v2.2.4/TIXI-2.2.4-macOS.tar.gz '
  - '[ "$TRAVIS_OS_NAME" != osx ] || tar xf Qt5.4_clang64_macOS.tar.gz'
  - '[ "$TRAVIS_OS_NAME" != osx ] || tar xf oce.0.17.2.macos_static.tar.gz'
  - '[ "$TRAVIS_OS_NAME" != osx ] || tar xf TIXI-2.2.4-macOS.tar.gz '
  
before_script:
  - mkdir build
  - cd build

script: 
  - '[ "$TRAVIS_OS_NAME" != osx ] || export CMAKE_PREFIX_PATH=`pwd`/../TIXI-2.2.4-macOS:`pwd`/../oce.0.17.2.macos_static:`pwd`/../Qt5.4_clang64_macOS'
  - '[ "$TRAVIS_OS_NAME" != osx ] || export CXXFLAGS=-Wno-inconsistent-missing-override '
  - '[ "$TRAVIS_OS_NAME" != linux ] || jdk_switcher use oraclejdk8'
  - cmake -DTIGL_BUILD_TESTS=ON -DTIGL_BINDINGS_MATLAB=ON -DTIGL_BINDINGS_JAVA=ON -DCMAKE_INSTALL_PREFIX=`pwd`/install ..
  - make -j 4
  - '[ "$TRAVIS_OS_NAME" != linux ] || make install'
  - '[ "$TRAVIS_OS_NAME" != osx ] || export DYLD_LIBRARY_PATH=`pwd`/../TIXI-2.2.4-macOS/lib '
  - cd tests
  - ./TiGL-unittests --gtest_output=xml
  - cd ..
  - TERM=dumb make tigl-java-demo

