version: '{build}'

os: Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Release

build:
  verbosity: minimal

artifacts:
  - path: '*.zip'
    name: binaries
  - path: '*.exe'
    name: installer

deploy:
  - provider: FTP
    protocol: sftp
    host: frs.sourceforge.net
    username:
      secure: HZlK5sZGRgSoPQQI6EgdtsFtTj/ZAfdSPdLLxt8FeuE=
    password:
      secure: z0kfNd+oRq/PHvJumrSOpA==
    folder: files/Nightlies-Windows
    on:
      appveyor_scheduled_build: true

  - provider: Environment
    name: GitHub
    on:
      appveyor_repo_tag: true


install:
  - ps: |
      Write-Output "Configuration: $env:CONFIGURATION"
      Write-Output "Platform: $env:PLATFORM"
      $generator = "Visual Studio 14 2015"
      $ocedist = "oce.0.17.2.win32_msvc2015_static"
      $tixidist = "TIXI-2.2.4-vc2015-win32"
      $qtdist = "5.7/msvc2015"
      if ($env:PLATFORM -eq "x64")
      {
          $generator = "$generator Win64"
          $ocedist = "oce.0.17.2.win64_msvc2015_static"
          $tixidist = "TIXI-2.2.4-vc2015-win64"
          $qtdist = "5.7/msvc2015_64"
      }
      md c:\oce -Force | Out-Null
      md c:\tixi -Force | Out-Null
      If (!(Test-Path -Path "c:\oce\$ocedist")) {
        Write-Output "Downloading OCE"
        (new-object System.Net.WebClient).Downloadfile("https://sourceforge.net/projects/tigl/files/Thirdparty/$ocedist.7z", "c:\$ocedist.7z")
        Write-Output "Extract OCE"
        & 7z x -y "c:\$ocedist.7z" -oC:\oce\ > null
      }
      If (!(Test-Path -Path "c:\tixi\$tixidist")) {
        Write-Output "Downloading TiXI"
        (new-object System.Net.WebClient).Downloadfile("https://github.com/DLR-SC/tixi/releases/download/v2.2.4/$tixidist.zip", "c:\$tixidist.zip")
        Write-Output "Extract TiXI"
        & 7z x -y "c:\$tixidist.zip" -oC:\tixi\ > null
      }
      If (!(Test-Path -Path "c:\doxygen-win")) {
        Write-Output "Downloading Doxygen"
        (new-object System.Net.WebClient).Downloadfile("https://sourceforge.net/projects/tigl/files/Thirdparty/doxygen-win.zip", "c:\doxygen-win.zip")
        Write-Output "Extract Doxygen"
        & 7z x -y "c:\doxygen-win.zip" -oC:\ > null
      }
  # check if release build, if yes we need nsis
  - ps: |
      $BUILD_RELEASE = $($env:appveyor_repo_tag -eq "true")
      $BUILD_NIGHTLY = "ON"
      if ($BUILD_RELEASE) {
        $BUILD_NIGHTLY = "OFF"
        Write-Output "Release builds enabled."
      }

build_script:
- ps: |
    md _build -Force | Out-Null
    cd _build
    Write-Output "Running cmake: -DCMAKE_INSTALL_PREFIX=install -DCASROOT=c:\oce\$ocedist -DTIXI_PATH=c:\tixi\$tixidist -DTIGL_BINDINGS_MATLAB=ON -DTIGL_BINDINGS_JAVA=ON -DTIGL_BUILD_TESTS=ON -DTIGL_NIGHTLY=$BUILD_NIGHTLY -DQT_PATH=c:\Qt\$qtdist -DDOXYGEN_EXECUTABLE=c:/doxygen-win/bin/doxygen.exe .."
    & cmake -G "$generator" -DCMAKE_INSTALL_PREFIX=install -DCASROOT=c:\oce\$ocedist -DTIXI_PATH=c:\tixi\$tixidist -DTIGL_BINDINGS_MATLAB=ON -DTIGL_BINDINGS_JAVA=ON -DTIGL_BUILD_TESTS=ON -DTIGL_NIGHTLY="$BUILD_NIGHTLY" -DQT_PATH=c:\Qt\$qtdist -DDOXYGEN_EXECUTABLE=c:/doxygen-win/bin/doxygen.exe ..
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
    & cmake --build . --config $env:CONFIGURATION --target install
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }


test_script:
- ps: |
    cd tests
    $env:PATH = "c:\tixi\$tixidist\bin;$env:PATH"
    & $env:CONFIGURATION\TiGL-unittests.exe --gtest_output=xml:test_results.xml
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
    (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test_results.xml))
    cd ..
    cmake --build . --target tigl-java-demo
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }

after_test:
- ps: |
    & cmake --build . --config $env:CONFIGURATION --target doc
    & cpack -G ZIP
    & mv *.zip ..
- ps : |
    if ($BUILD_RELEASE)
    {
        cpack -G NSIS
        mv *.exe ..
    }

cache:
 - c:\oce -> appveyor.yml
 - c:\tixi -> appveyor.yml
 - c:\redist
 - c:\doxygen-win
