version: '{build}'

os: Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Release
#  - Debug

build:
  verbosity: minimal

artifacts:
  - path: '_build/*.zip'
    name: binaries

install:
  - ps: |
      Write-Output "Configuration: $env:CONFIGURATION"
      Write-Output "Platform: $env:PLATFORM"
      $generator = "Visual Studio 10 2010"
      $ocedist = "oce.017.win32_msvc2010_static"
      $ocebindir = "Win32"
      $tixidist = "TIXI-2.2.4-win32"
      $qtdist = "msvc2010_opengl_32"
      $redist = "msvc10-redist"
      if ($env:PLATFORM -eq "x64")
      {
          $generator = "$generator Win64"
          $ocedist = "oce.017.win64_msvc2010_static"
          $ocebindir = "Win64"
          $tixidist = "TIXI-2.2.4-win64"
          $qtdist = "msvc2010_opengl_64"
      }
      md c:\oce -Force | Out-Null
      md c:\tixi -Force | Out-Null
      md c:\Qt\5.4.1 -Force | Out-Null
      md c:\redist -Force | Out-Null
      If (!(Test-Path -Path "c:\oce\$ocedist")) {
        Write-Output "Downloading OCE"
        (new-object System.Net.WebClient).Downloadfile("https://sourceforge.net/projects/tigl/files/Thirdparty/$ocedist.7z", "c:\$ocedist.7z")
        Write-Output "Extract OCE"
        & 7z x -y "c:\$ocedist.7z" -oC:\oce\ > null
      }
      If (!(Test-Path -Path "c:\tixi\$tixidist")) {
        Write-Output "Downloading TiXI"
        (new-object System.Net.WebClient).Downloadfile("https://github.com/DLR-SC/tixi/releases/download/v2.2.4/$tixidist.zip", "c:\$tixidist.zip")
        Write-Output "Extract TiXI"
        & 7z x -y "c:\$tixidist.zip" -oC:\tixi\ > null
      }
      If (!(Test-Path -Path "c:\Qt\5.4.1\$qtdist")) {
        Write-Output "Downloading Qt 5.4.1"
        (new-object System.Net.WebClient).Downloadfile("https://sourceforge.net/projects/tigl/files/Thirdparty/qt5.4_$qtdist.7z", "c:\qt5.4_$qtdist.7z")
        Write-Output "Extract Qt 5.4.1"
        & 7z x -y "c:\qt5.4_$qtdist.7z" -oC:\Qt\5.4.1\ > null
      }
      If (!(Test-Path -Path "c:\redist\$redist")) {
        Write-Output "Downloading VC 2010 Redistributable"
        (new-object System.Net.WebClient).Downloadfile("https://sourceforge.net/projects/tigl/files/Thirdparty/$redist.7z", "c:\$redist.7z")
        Write-Output "Extract VC 2010 Redistributable"
        & 7z x -y "c:\$redist.7z" -oC:\redist\ > null
      if (!(Test-Path -Path "c:\doxygen-win")) {
        Write-Output "Downloading Doxygen"
        (new-object System.Net.WebClient).Downloadfile("https://sourceforge.net/projects/tigl/files/Thirdparty/doxygen-win.zip", "c:\doxygen-win.zip")
        Write-Output "Extract Doxygen"
        & 7z x -y "c:\doxygen-win.zip" -oC:\ > null
      }


build_script:
- ps: |
    md _build -Force | Out-Null
    cd _build
    Write-Output "Running cmake: -DCASROOT=c:\oce\$ocedist -DTIXI_PATH=c:\tixi\$tixidist -DTIGL_BINDINGS_MATLAB=ON -DTIGL_BUILD_TESTS=ON -DTIGL_NIGHTLY=ON -DQT_PATH=c:\Qt\5.4.1\$qtdist -DDOXYGEN_EXECUTABLE=c:/doxygen-win/bin/doxygen.exe -DMSVC10_REDIST_DIR=c:/redist/$redist .."
    & cmake -G "$generator" -DCASROOT=c:\oce\$ocedist -DTIXI_PATH=c:\tixi\$tixidist -DTIGL_BINDINGS_MATLAB=ON -DTIGL_BUILD_TESTS=ON -DTIGL_NIGHTLY=ON -DQT_PATH=c:\Qt\5.4.1\$qtdist -DDOXYGEN_EXECUTABLE=c:/doxygen-win/bin/doxygen.exe -DMSVC10_REDIST_DIR=c:/redist/$redist ..
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
    & cmake --build . --config $env:CONFIGURATION
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }


test_script:
- ps: |
    cd tests
    $env:PATH = "c:\oce\$ocedist\$ocebindir\bin;c:\tixi\$tixidist\bin;$env:PATH"
    & $env:CONFIGURATION\TIGL-unittests.exe --gtest_output=xml:test_results.xml
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
    (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test_results.xml))
    cd ..

after_test:
- ps: |
    & cmake --build . --config $env:CONFIGURATION --target doc
    & cpack -G ZIP

cache:
 - c:\oce
 - c:\Qt\5.4.1
 - c:\tixi -> appveyor.yml
 - c:\redist
 - c:\doxygen-win
